apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "clusterissuers.name" . }}
  labels:
    {{- include "clusterissuers.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "clusterissuers.name" . }}
    {{- if .Values.production.enabled }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass | default "nginx" }}
